var header = document.getElementById("header").innerHTML

header.innerHTML =
"<h1>Edugame</h1>"
+ "<nav class=\"nav\">"
    + "<div class=\"navselect drop\">"
        + "<button class=\"dropbtn\" onclick=\"openPage('index.html')\">Home</button>"
    + "</div>"
    + "<div class=\"navselect drop\">"
        + "<button class=\"dropbtn\" onclick=\"openPage('template.html')\">Example Lesson</button>"
    + "</div>"
    + "<div class=\"navselect drop\">"
        + "<button class=\"dropbtn\">Grade</button>"
        + "<div class=\"drop-dropbox\">"
            + "<p class=\"drop-content\" onclick=\"openPage('g1.html')\">Grade 1</p>"
            + "<p class=\"drop-content\">Grade 2</p>"
            + "<p class=\"drop-content\">Grade 3</p>"
            + "<p class=\"drop-content\">Grade 4</p>"
        + "</div>"
    + "</div>"
    + "<div class=\"navselect drop\">"
        + "<button class=\"dropbtn\">Subject</button>"
        + "<div class=\"drop-dropbox\">"
            + "<p class=\"drop-content\">Maths</p>"
            + "<p class=\"drop-content\">English</p>"
            + "<p class=\"drop-content\">Humanities</p>"
            + "<p class=\"drop-content\">Science</p>"
        + "</div>"
    + "</div>"
    + "<div class=\"navselect drop\">"
        + "<button class=\"dropbtn\">About</button>"
        + "<div class=\"drop-dropbox\">"
            + "<p class=\"drop-content\">App</p>"
            + "<p class=\"drop-content\">Creators</p>"
        + "</div>"
    + "</div>"
+ "</nav>";
